<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<CodeMetricsProfile>legacy-samples-baseline</CodeMetricsProfile>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<!--
	<ItemGroup>
		<PackageReference Include="htmxor" Version="0.0.0-*" />
	</ItemGroup>
	-->

	<ItemGroup>
		<ProjectReference Include="..\..\src\Htmxor\Htmxor.csproj" />
		<ProjectReference Include="..\..\src\Htmxor.Generators\Htmxor.Generators.csproj"
		                  OutputItemType="Analyzer"
		                  ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
