using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Htmxor.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class HtmxorPutActionGenerator : IIncrementalGenerator
{
	private static readonly DiagnosticDescriptor UnsupportedDeclaration = new(
		"HTMXOR002",
		"Unsupported component-owned PUT action declaration",
		"Unsupported component-owned PUT action declaration: {0}",
		"Htmxor.Generators",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true,
		customTags: new[] { WellKnownDiagnosticTags.NotConfigurable });

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var declarations = context.AdditionalTextsProvider
			.Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
			.Combine(context.AnalyzerConfigOptionsProvider)
			.Select(static (input, cancellationToken) => HtmxorPutActionDeclaration.Parse(
				input.Left,
				ProjectRootComponentManifest.GetTypeName(input.Left, input.Right),
				cancellationToken))
			.Where(static declaration => declaration is not null)
			.Select(static (declaration, _) => declaration!)
			.Collect();

		context.RegisterSourceOutput(declarations, Emit);
	}

	private static void Emit(
		SourceProductionContext context,
		ImmutableArray<HtmxorPutActionDeclaration> declarations)
	{
		var ordered = declarations
			.OrderBy(static declaration => declaration.Path, StringComparer.Ordinal)
			.ThenBy(static declaration => declaration.Span.Start)
			.ToArray();
		var unsupported = ordered
			.Where(static declaration => declaration.UnsupportedReason is not null)
			.ToArray();
		if (unsupported.Length > 0)
		{
			ReportUnsupported(context, unsupported);
			return;
		}

		if (ordered.Length > 1)
		{
			ReportUnsupported(
				context,
				ordered,
				"exactly one component-owned PUT action is supported");
			return;
		}

		if (ordered.Length == 1)
		{
			context.AddSource(
				"HtmxorGeneratedPutAction.g.cs",
				SourceText.From(Render(ordered[0]), Encoding.UTF8));
		}
	}

	private static void ReportUnsupported(
		SourceProductionContext context,
		IEnumerable<HtmxorPutActionDeclaration> declarations,
		string? sharedReason = null)
	{
		foreach (var declaration in declarations)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				UnsupportedDeclaration,
				Location.Create(declaration.Path, declaration.Span, declaration.LineSpan),
				sharedReason ?? declaration.UnsupportedReason));
		}
	}

	private static string Render(HtmxorPutActionDeclaration declaration)
	{
		var typeName = declaration.ComponentTypeName;
		var separator = typeName.LastIndexOf('.');
		var componentNamespace = separator < 0 ? null : typeName.Substring(0, separator);
		var componentName = separator < 0 ? typeName : typeName.Substring(separator + 1);
		var handlerName = declaration.HandlerName!;
		var handlerIdentity = typeName + ".PUT." + handlerName;
		var componentSource = RenderComponent(
			componentNamespace,
			componentName,
			typeName,
			handlerName,
			handlerIdentity);

		return
			$$"""
			// <auto-generated/>
			#nullable enable

			namespace Microsoft.AspNetCore.Builder
			{
				internal static partial class HtmxorGeneratedRouteRegistrationExtensions
				{
					static partial void AddGeneratedActions(
						global::System.Collections.Generic.ICollection<global::Htmxor.Builder.HtmxorGeneratedComponentAction> actions)
						=> actions.Add(global::{{typeName}}.__HtmxorGeneratedPutAction);
				}
			}

			{{componentSource}}
			""";
	}

	private static string RenderComponent(
		string? componentNamespace,
		string componentName,
		string typeName,
		string handlerName,
		string handlerIdentity)
	{
		var namespaceStart = componentNamespace is null
			? string.Empty
			: "namespace " + componentNamespace + "\n{\n";
		var namespaceEnd = componentNamespace is null ? string.Empty : "}\n";
		var indent = componentNamespace is null ? string.Empty : "\t";
		var escapedHandlerIdentity = EscapeStringLiteral(handlerIdentity);
		return
			$$"""
			{{namespaceStart}}{{indent}}public partial class {{componentName}} : global::Microsoft.AspNetCore.Components.IComponent
			{{indent}}{
			{{indent}}	internal static global::Htmxor.Builder.HtmxorGeneratedComponentAction __HtmxorGeneratedPutAction { get; } = new(
			{{indent}}		typeof(global::{{typeName}}),
			{{indent}}		"PUT",
			{{indent}}		"{{escapedHandlerIdentity}}");

			{{indent}}	[global::Microsoft.AspNetCore.Components.InjectAttribute]
			{{indent}}	private global::Htmxor.Endpoints.IHtmxorGeneratedComponentActionRequest __HtmxorGeneratedActionRequest { get; set; } = default!;

			{{indent}}	[global::Microsoft.AspNetCore.Components.InjectAttribute]
			{{indent}}	private global::Htmxor.Http.HtmxContext __HtmxorGeneratedContext { get; set; } = default!;

			{{indent}}	async global::System.Threading.Tasks.Task global::Microsoft.AspNetCore.Components.IComponent.SetParametersAsync(
			{{indent}}		global::Microsoft.AspNetCore.Components.ParameterView parameters)
			{{indent}}	{
			{{indent}}		await SetParametersAsync(parameters);
			{{indent}}		if (__HtmxorGeneratedActionRequest.TryConsume(__HtmxorGeneratedPutAction))
			{{indent}}		{
			{{indent}}			var callback = global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Htmxor.HtmxEventArgs>(this, {{handlerName}});
			{{indent}}			await callback.InvokeAsync(new global::Htmxor.HtmxEventArgs(__HtmxorGeneratedContext));
			{{indent}}		}
			{{indent}}	}
			{{indent}}}
			{{namespaceEnd}}
			""";
	}

	private static string EscapeStringLiteral(string value)
		=> value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n");
}
