using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Htmxor.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class HtmxorActionGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var declarationSets = context.AdditionalTextsProvider
			.Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
			.Combine(context.AnalyzerConfigOptionsProvider)
			.Select(static (input, cancellationToken) => HtmxorComponentActionDeclaration.ParseAll(
				input.Left,
				ProjectRootComponentManifest.GetTypeName(input.Left, input.Right),
				cancellationToken))
			.Collect();

		context.RegisterSourceOutput(declarationSets, Emit);
	}

	private static void Emit(
		SourceProductionContext context,
		ImmutableArray<ImmutableArray<HtmxorComponentActionDeclaration>> declarationSets)
	{
		var ordered = declarationSets
			.SelectMany(static declarations => declarations)
			.OrderBy(static declaration => declaration.Path, StringComparer.Ordinal)
			.ThenBy(static declaration => declaration.Span.Start)
			.ToArray();
		var unsupported = ordered
			.Where(static declaration => declaration.UnsupportedReason is not null)
			.ToArray();
		if (unsupported.Length > 0)
		{
			ReportUnsupported(context, unsupported);
			return;
		}

		if (ordered.Length > 0)
		{
			context.AddSource(
				"HtmxorGeneratedActions.g.cs",
				SourceText.From(Render(ordered), Encoding.UTF8));
		}
	}

	private static void ReportUnsupported(
		SourceProductionContext context,
		IEnumerable<HtmxorComponentActionDeclaration> declarations)
	{
		foreach (var declaration in declarations)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				HtmxorActionDeclarationAnalyzer.UnsupportedDeclaration,
				Location.Create(declaration.Path, declaration.Span, declaration.LineSpan),
				declaration.UnsupportedReason));
		}
	}

	private static string Render(IReadOnlyList<HtmxorComponentActionDeclaration> declarations)
	{
		var registrations = string.Concat(declarations.Select(static declaration =>
			"\t\t\tactions.Add(global::" + declaration.ComponentTypeName + "." +
			GetActionPropertyName(declaration.HttpMethod) + ");\n"));
		var components = string.Join(
			"\n",
			declarations
				.GroupBy(static declaration => declaration.ComponentTypeName, StringComparer.Ordinal)
				.Select(RenderComponent));

		return
			$$"""
			// <auto-generated/>
			#nullable enable

			namespace Microsoft.AspNetCore.Builder
			{
				internal static partial class HtmxorGeneratedRouteRegistrationExtensions
				{
					static partial void AddGeneratedActions(
						global::System.Collections.Generic.ICollection<global::Htmxor.Builder.HtmxorGeneratedComponentAction> actions)
					{
			{{registrations}}			}
				}
			}

			{{components}}
			""";
	}

	private static string RenderComponent(
		IGrouping<string, HtmxorComponentActionDeclaration> componentActions)
	{
		var declarations = componentActions.ToArray();
		var typeName = componentActions.Key;
		var separator = typeName.LastIndexOf('.');
		var componentNamespace = separator < 0 ? null : typeName.Substring(0, separator);
		var componentName = separator < 0 ? typeName : typeName.Substring(separator + 1);
		var namespaceStart = componentNamespace is null
			? string.Empty
			: "namespace " + componentNamespace + "\n{\n";
		var namespaceEnd = componentNamespace is null ? string.Empty : "}\n";
		var indent = componentNamespace is null ? string.Empty : "\t";
		var actionProperties = string.Concat(declarations.Select(declaration =>
			RenderActionProperty(declaration, indent)));
		var dispatch = string.Concat(declarations.Select(declaration =>
			RenderDispatch(declaration, indent)));

		return
			$$"""
			{{namespaceStart}}{{indent}}public partial class {{componentName}} : global::Microsoft.AspNetCore.Components.IComponent
			{{indent}}{
			{{actionProperties}}
			{{indent}}	[global::Microsoft.AspNetCore.Components.InjectAttribute]
			{{indent}}	private global::Htmxor.Endpoints.IHtmxorGeneratedComponentActionRequest __HtmxorGeneratedActionRequest { get; set; } = default!;

			{{indent}}	[global::Microsoft.AspNetCore.Components.InjectAttribute]
			{{indent}}	private global::Htmxor.Http.HtmxContext __HtmxorGeneratedContext { get; set; } = default!;

			{{indent}}	async global::System.Threading.Tasks.Task global::Microsoft.AspNetCore.Components.IComponent.SetParametersAsync(
			{{indent}}		global::Microsoft.AspNetCore.Components.ParameterView parameters)
			{{indent}}	{
			{{indent}}		await SetParametersAsync(parameters);
			{{dispatch}}	{{indent}}	}
			{{indent}}}
			{{namespaceEnd}}
			""";
	}

	private static string RenderActionProperty(
		HtmxorComponentActionDeclaration declaration,
		string indent)
	{
		var propertyName = GetActionPropertyName(declaration.HttpMethod);
		var handlerIdentity = EscapeStringLiteral(
			declaration.ComponentTypeName + "." + declaration.HttpMethod + "." + declaration.HandlerName);
		var usesStockRoute = declaration.UsesStockRoute ? "true" : "false";
		return
			$"{indent}\tinternal static global::Htmxor.Builder.HtmxorGeneratedComponentAction {propertyName} {{ get; }} = new(\n" +
			$"{indent}\t\ttypeof(global::{declaration.ComponentTypeName}),\n" +
			$"{indent}\t\t\"{declaration.HttpMethod}\",\n" +
			$"{indent}\t\t\"{handlerIdentity}\",\n" +
			$"{indent}\t\t{usesStockRoute});\n\n";
	}

	private static string RenderDispatch(
		HtmxorComponentActionDeclaration declaration,
		string indent)
	{
		var propertyName = GetActionPropertyName(declaration.HttpMethod);
		return
			$"{indent}\t\tif (__HtmxorGeneratedActionRequest.TryConsume({propertyName}))\n" +
			$"{indent}\t\t{{\n" +
			$"{indent}\t\t\tvar callback = global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Htmxor.HtmxEventArgs>(this, {declaration.HandlerName});\n" +
			$"{indent}\t\t\tawait callback.InvokeAsync(new global::Htmxor.HtmxEventArgs(__HtmxorGeneratedContext));\n" +
			$"{indent}\t\t}}\n";
	}

	private static string GetActionPropertyName(string httpMethod)
		=> "__HtmxorGenerated" + httpMethod.Substring(0, 1) +
			httpMethod.Substring(1).ToLowerInvariant() + "Action";

	private static string EscapeStringLiteral(string value)
		=> value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n");
}
