using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Htmxor.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class HtmxorPutActionGenerator : IIncrementalGenerator
{
	private static readonly DiagnosticDescriptor UnsupportedDeclaration = new(
		"HTMXOR002",
		"Unsupported component-owned PUT action declaration",
		"Unsupported component-owned PUT action declaration: {0}",
		"Htmxor.Generators",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true,
		customTags: new[] { WellKnownDiagnosticTags.NotConfigurable });

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var declarations = context.AdditionalTextsProvider
			.Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
			.Combine(context.AnalyzerConfigOptionsProvider)
			.Select(static (input, cancellationToken) => HtmxorPutActionDeclaration.Parse(
				input.Left,
				ProjectRootComponentManifest.GetTypeName(input.Left, input.Right),
				cancellationToken))
			.Where(static declaration => declaration is not null)
			.Select(static (declaration, _) => declaration!)
			.Collect();

		context.RegisterSourceOutput(declarations, Emit);
	}

	private static void Emit(
		SourceProductionContext context,
		ImmutableArray<HtmxorPutActionDeclaration> declarations)
	{
		var ordered = declarations
			.OrderBy(static declaration => declaration.Path, StringComparer.Ordinal)
			.ThenBy(static declaration => declaration.Span.Start)
			.ToArray();
		var unsupported = ordered
			.Where(static declaration => declaration.UnsupportedReason is not null)
			.ToArray();
		if (unsupported.Length > 0)
		{
			ReportUnsupported(context, unsupported);
			return;
		}

		if (ordered.Length > 1)
		{
			ReportUnsupported(
				context,
				ordered,
				"exactly one component-owned PUT action is supported");
			return;
		}

		if (ordered.Length == 1)
		{
			context.AddSource(
				"HtmxorGeneratedPutAction.g.cs",
				SourceText.From(Render(ordered[0]), Encoding.UTF8));
		}
	}

	private static void ReportUnsupported(
		SourceProductionContext context,
		IEnumerable<HtmxorPutActionDeclaration> declarations,
		string? sharedReason = null)
	{
		foreach (var declaration in declarations)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				UnsupportedDeclaration,
				Location.Create(declaration.Path, declaration.Span, declaration.LineSpan),
				sharedReason ?? declaration.UnsupportedReason));
		}
	}

	private static string Render(HtmxorPutActionDeclaration declaration)
	{
		var typeName = declaration.ComponentTypeName;
		var separator = typeName.LastIndexOf('.');
		var componentNamespace = separator < 0 ? null : typeName.Substring(0, separator);
		var componentName = separator < 0 ? typeName : typeName.Substring(separator + 1);
		var handlerName = declaration.HandlerName!;
		var handlerIdentity = typeName + ".PUT." + handlerName;
		var componentSource = RenderComponent(
			componentNamespace,
			componentName,
			typeName,
			handlerName,
			handlerIdentity);

		return "// <auto-generated/>\n" +
			"#nullable enable\n\n" +
			"namespace Microsoft.AspNetCore.Builder\n" +
			"{\n" +
			"\tinternal static partial class HtmxorGeneratedRouteRegistrationExtensions\n" +
			"\t{\n" +
			"\t\tstatic partial void AddGeneratedActions(\n" +
			"\t\t\tglobal::System.Collections.Generic.ICollection<" +
			"global::Htmxor.Builder.HtmxorGeneratedComponentAction> actions)\n" +
			"\t\t\t=> actions.Add(global::" + typeName + ".__HtmxorGeneratedPutAction);\n" +
			"\t}\n" +
			"}\n\n" +
			componentSource;
	}

	private static string RenderComponent(
		string? componentNamespace,
		string componentName,
		string typeName,
		string handlerName,
		string handlerIdentity)
	{
		var namespaceStart = componentNamespace is null
			? string.Empty
			: "namespace " + componentNamespace + "\n{\n";
		var namespaceEnd = componentNamespace is null ? string.Empty : "}\n";
		var indent = componentNamespace is null ? string.Empty : "\t";
		return namespaceStart +
			indent + "public partial class " + componentName +
			" : global::Microsoft.AspNetCore.Components.IComponent\n" +
			indent + "{\n" +
			indent + "\tinternal static global::Htmxor.Builder.HtmxorGeneratedComponentAction " +
			"__HtmxorGeneratedPutAction { get; } = new(\n" +
			indent + "\t\ttypeof(global::" + typeName + "),\n" +
			indent + "\t\t\"PUT\",\n" +
			indent + "\t\t\"" + EscapeStringLiteral(handlerIdentity) + "\");\n\n" +
			indent + "\t[global::Microsoft.AspNetCore.Components.InjectAttribute]\n" +
			indent + "\tprivate global::Htmxor.Endpoints.IHtmxorGeneratedComponentActionRequest " +
			"__HtmxorGeneratedActionRequest { get; set; } = default!;\n\n" +
			indent + "\t[global::Microsoft.AspNetCore.Components.InjectAttribute]\n" +
			indent + "\tprivate global::Htmxor.Http.HtmxContext " +
			"__HtmxorGeneratedContext { get; set; } = default!;\n\n" +
			indent + "\tasync global::System.Threading.Tasks.Task " +
			"global::Microsoft.AspNetCore.Components.IComponent.SetParametersAsync(\n" +
			indent + "\t\tglobal::Microsoft.AspNetCore.Components.ParameterView parameters)\n" +
			indent + "\t{\n" +
			indent + "\t\tawait SetParametersAsync(parameters);\n" +
			indent + "\t\tif (__HtmxorGeneratedActionRequest.TryConsume(__HtmxorGeneratedPutAction))\n" +
			indent + "\t\t{\n" +
			indent + "\t\t\tvar callback = global::Microsoft.AspNetCore.Components.EventCallback.Factory." +
			"Create<global::Htmxor.HtmxEventArgs>(this, " + handlerName + ");\n" +
			indent + "\t\t\tawait callback.InvokeAsync(" +
			"new global::Htmxor.HtmxEventArgs(__HtmxorGeneratedContext));\n" +
			indent + "\t\t}\n" +
			indent + "\t}\n" +
			indent + "}\n" +
			namespaceEnd;
	}

	private static string EscapeStringLiteral(string value)
		=> value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n");
}
