using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Htmxor.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class HtmxorRouteGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var razorComponents = context.AdditionalTextsProvider
			.Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
			.Collect();
		var csharpComponents = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Htmxor.HtmxRouteAttribute",
				static (_, _) => true,
				static (attributeContext, _) =>
					HtmxorRouteManifest.GetCSharpComponent(attributeContext))
			.WithTrackingName("CSharpRouteCandidates")
			.Where(static component => component is not null)
			.Select(static (component, _) => component!)
			.Collect();
		var projectRootComponents = razorComponents
			.Combine(csharpComponents)
			.Combine(context.AnalyzerConfigOptionsProvider);

		context.RegisterSourceOutput(
			projectRootComponents,
			static (productionContext, input) => Emit(
				productionContext,
				HtmxorRouteManifest.GetTypeNames(
					input.Left.Left,
					input.Left.Right,
					input.Right)));
	}

	private static void Emit(
		SourceProductionContext context,
		ImmutableArray<string> projectRootComponentTypeNames)
	{
		if (projectRootComponentTypeNames.IsDefaultOrEmpty)
		{
			return;
		}

		context.AddSource(
			"HtmxorGeneratedRouteRegistration.g.cs",
			SourceText.From(Render(projectRootComponentTypeNames), Encoding.UTF8));
	}

	private static string Render(ImmutableArray<string> projectRootComponentTypeNames)
	{
		var manifest = string.Concat(projectRootComponentTypeNames.Select(static typeName =>
			"\t\t\"" + EscapeStringLiteral(typeName) + "\",\n"));
		return "// <auto-generated/>\n" +
			"#nullable enable\n\n" +
			"namespace Microsoft.AspNetCore.Builder;\n\n" +
			"internal static partial class HtmxorGeneratedRouteRegistrationExtensions\n" +
			"{\n" +
			"\tprivate static readonly string[] ProjectRootComponentTypeNames =\n" +
			"\t[\n" +
			manifest +
			"\t];\n\n" +
			"\tinternal static global::Microsoft.AspNetCore.Builder.RazorComponentsEndpointConventionBuilder " +
			"AddHtmxorComponentEndpoints(\n" +
			"\t\tthis global::Microsoft.AspNetCore.Builder.RazorComponentsEndpointConventionBuilder builder,\n" +
			"\t\tglobal::Microsoft.AspNetCore.Routing.RouteGroupBuilder endpoints)\n" +
			"\t{\n" +
			"\t\tvar generatedActions = new global::System.Collections.Generic.List<" +
			"global::Htmxor.Builder.HtmxorGeneratedComponentAction>();\n" +
			"\t\tAddGeneratedActions(generatedActions);\n" +
			"\t\treturn global::Microsoft.AspNetCore.Builder." +
			"HtmxorComponentEndpointRouteBuilderExtensions.AddHtmxorAttributedComponentEndpoints(\n" +
			"\t\t\tbuilder,\n" +
			"\t\t\tendpoints,\n" +
			"\t\t\ttypeof(HtmxorGeneratedRouteRegistrationExtensions).Assembly,\n" +
			"\t\t\tProjectRootComponentTypeNames,\n" +
			"\t\t\tgeneratedActions);\n" +
			"\t}\n\n" +
			"\tstatic partial void AddGeneratedActions(\n" +
			"\t\tglobal::System.Collections.Generic.ICollection<" +
			"global::Htmxor.Builder.HtmxorGeneratedComponentAction> actions);\n" +
			"}\n";
	}

	private static string EscapeStringLiteral(string value)
		=> value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n");
}
