using System;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Htmxor.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class HtmxorRouteGenerator : IIncrementalGenerator
{
	private static readonly DiagnosticDescriptor UnsupportedDeclaration = new(
		"HTMXOR001",
		"Unsupported HTMX-only route declaration",
		"The issue #93 tracer supports one project-root component without @page, one literal constrained HtmxRoute with explicit GET only, and one literal Authorize policy",
		"Htmxor.Generators",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Razor and Htmxor generators run in the same unordered pass, so consume the raw Razor input.
		var declarations = context.AdditionalTextsProvider
			.Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
			.Select(static (file, cancellationToken) => RouteDeclaration.Read(file, cancellationToken))
			.Where(static declaration => declaration.HasDeclaration)
			.Collect()
			.Combine(context.AnalyzerConfigOptionsProvider);

		context.RegisterSourceOutput(
			declarations,
			static (productionContext, input) => Emit(productionContext, input.Left, input.Right));
	}

	private static void Emit(
		SourceProductionContext context,
		ImmutableArray<RouteDeclaration> declarations,
		AnalyzerConfigOptionsProvider optionsProvider)
	{
		if (declarations.Length != 1)
		{
			ReportUnsupportedDeclarations(context, declarations);
			return;
		}

		var declaration = declarations[0];
		if (!TryGetProject(optionsProvider, out var project) ||
			!declaration.IsSupported ||
			!string.Equals(
			Path.GetDirectoryName(declaration.Path),
			project.ProjectDirectory,
			StringComparison.OrdinalIgnoreCase))
		{
			context.ReportDiagnostic(Diagnostic.Create(UnsupportedDeclaration, declaration.Location));
			return;
		}

		context.AddSource(
			"Issue91GeneratedRoute.g.cs",
			SourceText.From(Render(project.RootNamespace, declaration), Encoding.UTF8));
	}

	private static void ReportUnsupportedDeclarations(
		SourceProductionContext context,
		ImmutableArray<RouteDeclaration> declarations)
	{
		foreach (var declaration in declarations)
		{
			context.ReportDiagnostic(Diagnostic.Create(UnsupportedDeclaration, declaration.Location));
		}
	}

	private static bool TryGetProject(
		AnalyzerConfigOptionsProvider optionsProvider,
		out ProjectInput project)
	{
		var options = optionsProvider.GlobalOptions;
		var hasRootNamespace = options.TryGetValue("build_property.RootNamespace", out var rootNamespace);
		var hasProjectDirectory = options.TryGetValue(
			"build_property.MSBuildProjectDirectory",
			out var projectDirectory);
		project = new ProjectInput(rootNamespace ?? string.Empty, projectDirectory ?? string.Empty);

		return hasRootNamespace && hasProjectDirectory;
	}

	private static string Render(string rootNamespace, RouteDeclaration declaration)
	{
		var route = EscapeStringLiteral(declaration.Route);
		var policy = EscapeStringLiteral(declaration.Policy);
		return "// <auto-generated/>\n" +
			"#nullable enable\n\n" +
			"namespace Microsoft.AspNetCore.Builder;\n\n" +
			"internal static class HtmxorGeneratedRouteRegistrationExtensions\n" +
			"{\n" +
			"\tinternal static global::Microsoft.AspNetCore.Builder.RazorComponentsEndpointConventionBuilder " +
			"AddHtmxorComponentEndpoints(\n" +
			"\t\tthis global::Microsoft.AspNetCore.Builder.RazorComponentsEndpointConventionBuilder builder,\n" +
			"\t\tglobal::Microsoft.AspNetCore.Routing.RouteGroupBuilder endpoints)\n" +
			"\t{\n" +
			"\t\tvar configured = global::Microsoft.AspNetCore.Builder." +
			"HtmxorComponentEndpointRouteBuilderExtensions.AddHtmxorComponentEndpoints(\n" +
			"\t\t\tbuilder,\n" +
			"\t\t\t(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)endpoints);\n" +
			"\t\tglobal::Microsoft.AspNetCore.Builder.HtmxorComponentEndpointRouteBuilderExtensions." +
			"MapHtmxorGeneratedComponentEndpoint(\n" +
			"\t\t\tendpoints,\n" +
			"\t\t\ttypeof(global::" + rootNamespace + "." + declaration.ComponentName + "),\n" +
			"\t\t\t\"" + route + "\",\n" +
			"\t\t\t\"" + policy + "\");\n\n" +
			"\t\treturn configured;\n" +
			"\t}\n" +
			"}\n";
	}

	private static string EscapeStringLiteral(string value)
		=> value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n");

	private sealed class ProjectInput(string rootNamespace, string projectDirectory)
	{
		public string RootNamespace { get; } = rootNamespace;

		public string ProjectDirectory { get; } = projectDirectory;
	}
}
